#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    dpkg-divert --package universe-os --remove --rename \
        --divert /usr/share/universe-os/diverted/wine.desktop /usr/share/applications/wine.desktop || true
fi
exit 0
