---
displaymanagers:
  - lightdm
basicSetup: false
sysconfigSetup: false
defaultDesktopEnvironment:
    executable: "labwc"
    desktopFile: "universe"
lightdm:
  preferred_greeters: ["lightdm-gtk-greeter.desktop"]
