---
# Het eerste account wordt beheerder (groep sudo). Geen rootwachtwoord, geen automatische aanmelding.
userGroup: users
defaultGroups:
    - cdrom
    - sudo
    - audio
    - video
    - plugdev
    - netdev
    - { name: bluetooth, must_exist: false, system: true }
    - { name: lpadmin, must_exist: false, system: true }
    - { name: scanner, must_exist: false, system: true }
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: false
passwordRequirements:
    nonempty: true
    minLength: 6
    maxLength: -1
allowWeakPasswords: false
allowWeakPasswordsDefault: false
user:
    shell: /bin/bash
    forbidden_names: [ root, universe ]
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "universe-${product}"
    forbidden_names: [ localhost ]
