---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false
showDonateUrl: false
requirements:
    requiredStorage: 15
    requiredRam: 2.0
    check:
        - storage
        - ram
        - power
        - root
        - screen
    required:
        - storage
        - ram
        - root
# Geen internet nodig om te installeren.
geoip:
    style: "none"
languageIcon: languages
