# Universe OS installer (Calamares 3.3). Alleen in de live-omgeving; wordt na installeren verwijderd.
---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id: grub-offline
  module: shellprocess
  config: shellprocess-grub-offline.conf
- id: afronden
  module: shellprocess
  config: shellprocess-afronden.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - shellprocess@grub-offline
  - bootloader
  - packages
  - shellprocess@afronden
  - initramfscfg
  - initramfs
  - umount
- show:
  - finished

branding: universe
# Vlak voor het echte installeren vraagt de installer nog een keer om bevestiging.
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
