import {audioView} from './audio-ui.js';
import {updatesView} from './updates-ui.js';
import {call,on,h,icon,applySettings} from './api.js';
import {SETTINGS} from './settings-index.js';
const content=document.getElementById('content'),nav=document.getElementById('pages');
let config=null,current='appearance',generation=0;
const text=(value)=>value==null?'Onbekend':String(value);
const note=t=>h('p',{class:'muted'},t);
const card=(title,...items)=>h('section',{class:'card'},h('h3',{},title),...items);
const field=(title,input)=>h('label',{},title,input);
const input=(type='text',value='')=>h('input',{type,value,autocomplete:type==='password'?'off':undefined});
const check=(title,value=false)=>{const i=input('checkbox');i.checked=value;return {node:h('label',{class:'check'},i,title),i};};
const select=(options,value)=>{const s=h('select');for(const [v,name] of options)s.append(h('option',{value:String(v)},name));s.value=String(value);return s;};
function button(title,action){const message=h('p',{class:'message',role:'status'}),b=h('button',{type:'button'},title);b.addEventListener('click',async()=>{b.disabled=true;message.className='message';message.textContent='Bezig…';try{const outcome=await action();message.textContent=typeof outcome==='string'?outcome:'Gelukt.';}catch(e){message.className='message error';message.textContent=e.message;}finally{b.disabled=false;}});return h('div',{},b,message);}
function details(data,names){const dl=h('dl');for(const [key,name] of Object.entries(names))dl.append(h('dt',{},name),h('dd',{},text(({connected:'Verbonden',disconnected:'Niet verbonden',unavailable:'Niet beschikbaar',wifi:'Wifi',ethernet:'Netwerkkabel'})[data[key]]||data[key])));return dl;}
const tool=(label,name,args={})=>button(label,async()=>{await call('run',{tool:name,...args});return 'Programma geopend; de actie moet daar nog worden uitgevoerd.';});
async function save(key,value){config=await call('config.set',{key,value});applySettings({...config.settings,colors:config.world.colors});}
function setting(label,key,type,options){let i;if(type==='checkbox'){const c=check(label,config.settings[key]);return h('div',{},c.node,button('Opslaan',()=>save(key,c.i.checked)));}i=type==='select'?select(options,config.settings[key]):input('number',config.settings[key]);if(type!=='select'){i.min=options[0];i.max=options[1];i.step=options[2]||1;}return h('div',{},field(label,i),button('Opslaan',()=>{if(!i.checkValidity())throw Error('Controleer de waarde.');return save(key,type==='select'?i.value:Number(i.value));}));}
function passwords(title,command,args={},own=false){const old=input('password'),pw=input('password'),repeat=input('password');pw.minLength=6;return card(title,...(own?[field('Huidig wachtwoord',old)]:[]),field('Nieuw wachtwoord',pw),field('Herhaal nieuw wachtwoord',repeat),button('Wachtwoord wijzigen',async()=>{if(pw.value.length<6||pw.value!==repeat.value)throw Error('Gebruik minstens 6 tekens en twee gelijke wachtwoorden.');const payload=own?{current:old.value,new:pw.value}:{...args,password:pw.value};old.value=pw.value=repeat.value='';await call(command,payload);}));}
const pages={
 appearance:async root=>root.append(card('Vormgeving en beweging',setting('Animaties','animations','select',[['full','Volledig'],['reduced','Verminderd'],['off','Uit']]),setting('Reisanimaties','travel','checkbox'),setting('Interfacegrootte (%)','uiScale','number',[50,300]),setting('Tekstgrootte (%)','textScale','number',[75,250]),note('De aangepaste schaal wordt bij opnieuw openen van dit venster toegepast. Verminderde beweging schakelt zweven en parallax uit.'))),
 network:async root=>{const s=await call('network.status');root.append(card('Verbinding',details(s,{state:'Status',type:'Type',name:'Netwerk'}),tool('Verbindingen beheren','network-editor')));const networks=await call('wifi.list');if(!networks.length)root.append(note('Geen wifi-netwerken gevonden. Controleer de adapter via Verbindingen beheren.'));for(const n of networks){const pw=input('password');root.append(card(n.ssid,note(`${n.signal}% signaal${n.active?' · Verbonden':''}`),...(n.secure?[field('Wifi-wachtwoord',pw)]:[]),button('Verbinden',async()=>{const password=pw.value;pw.value='';await call('wifi.connect',{ssid:n.ssid,password});})));}},
 sound:async root=>{root.append(card('Geluidsuitgang',audioView()));const s=await call('status'),m=await call('mic.get');for(const [title,data,cmd] of [['Uitvoer',s.volume,'volume.set'],['Microfoon',m,'mic.set']]){if(!data){root.append(note(`${title}: geen beschikbaar apparaat gevonden.`));continue;}const i=input('number',data.level);i.min=0;i.max=100;root.append(card(title,note(data.muted?'Gedempt':'Niet gedempt'),field('Volume (%)',i),button('Volume toepassen',()=>{if(!i.checkValidity())throw Error('Kies 0 tot 100.');return call(cmd,{level:Number(i.value)});})));}root.append(button('Uitvoer dempen of aanzetten',()=>call('volume.mute')),tool('Apparaten en microfoondemping beheren','pavucontrol'));},
 displays:async root=>{const list=await call('displays.list');for(const d of list){const scale=input('number',d.scale);scale.min=.5;scale.max=3;scale.step=.25;root.append(card(d.description||d.name,note(`${d.name} · ${d.width||'?'}×${d.height||'?'} · ${d.enabled?'Aan':'Uit'}`),field('Schaalfactor',scale),button('Schaal toepassen',()=>{if(!scale.checkValidity())throw Error('Kies een schaal van 0,5 tot 3.');return call('displays.scale',{name:d.name,scale:Number(scale.value)});})));}if(!list.length)root.append(note('Geen beeldschermgegevens beschikbaar.'));root.append(tool('Resolutie en schermindeling beheren','wdisplays'));},
 bluetooth:async root=>{const s=await call('bluetooth.get');root.append(card('Bluetooth',note(s.adapter?'Bluetooth-adapter gevonden.':'Geen Bluetooth-adapter gevonden.'),tool('Apparaten koppelen en beheren','blueman-manager')));},
 keyboard:async root=>{const kb=await call('keyboard.get'),langs=await call('locale.get');const k=select(kb.list.map((v,i)=>[i,v.name]),kb.list.findIndex(v=>v.layout===kb.current.layout&&v.variant===kb.current.variant));const system=check('Ook toepassen als systeemstandaard (beheerdersrechten)');const lang=select(langs.list.map(v=>[v.id,v.name+(v.installed?'':' — nog niet geïnstalleerd')]),langs.current.lang);root.append(card('Toetsenbord',field('Indeling',k),system.node,button('Indeling toepassen',async()=>{const v=kb.list[Number(k.value)];await call('keyboard.set',{layout:v.layout,variant:v.variant,system:system.i.checked});}),field('Test hier letters en tekens',h('textarea',{rows:3,placeholder:'Typ bijvoorbeeld @ € é ë / ?'}))),card('Taal',field('Taal',lang),button('Taal toepassen',()=>call('locale.set',{lang:lang.value,system:system.i.checked})),note('Nieuwe taal wordt na opnieuw aanmelden gebruikt. Een ontbrekende taal moet eerst via Software worden geïnstalleerd.')));},
 mouse:async root=>root.append(card('Muis en touchpad',setting('Natuurlijk scrollen','naturalScroll','checkbox'),setting('Tikken om te klikken','tapToClick','checkbox'),setting('Aanwijzersnelheid (−1 tot 1)','pointerSpeed','number',[-1,1,.1]))),
 datetime:async root=>{const data=await call('timezone.get'),zone=select(data.zones.map(v=>[v,v]),data.zone);root.append(card('Datum en tijd',note(new Date().toLocaleString('nl-NL')),note(data.ntp?'Automatische tijdsynchronisatie staat aan.':'Automatische tijdsynchronisatie staat uit.'),field('Tijdzone',zone),button('Tijdzone wijzigen',()=>call('timezone.set',{zone:zone.value})),note('Wijzigen van de systeemtijd vereist beheerdersrechten.')));},
 power:async root=>{const s=await call('status');root.append(card('Energie',note(s.battery.present?`${s.battery.percent}% · ${s.battery.state}`:'Geen batterij aanwezig.'),setting('Automatisch vergrendelen na minuten (0 = nooit)','lockMinutes','number',[0,240]),setting('Scherm uit na minuten (0 = nooit)','screenOffMinutes','number',[0,240]),note(config.user.live?'In de live-sessie staat automatische vergrendeling uit.':'Automatisch vergrendelen gebruikt het wachtwoord van je account.')));},
 users:async root=>{const list=await call('users.list');for(const u of list){root.append(card(u.fullName||u.name,note(`${u.name} · ${u.admin?'Beheerder':'Standaardaccount'}${u.me?' · Jij':''}`)));if(u.me)root.append(passwords('Eigen wachtwoord','account.password',{},true));if(config.user.admin){root.append(passwords(`Wachtwoord van ${u.name}`,'users.password',{name:u.name}));const verify=input('text'),removeHome=check('Persoonlijke bestanden ook verwijderen (onomkeerbaar)');root.append(card(`Beheer ${u.name}`,button(u.admin?'Standaardaccount maken':'Beheerder maken',()=>call('users.admin',{name:u.name,admin:!u.admin})),field(`Typ ${u.name} om verwijderen te bevestigen`,verify),removeHome.node,button('Account verwijderen',async()=>{if(verify.value!==u.name)throw Error('Bevestig de exacte accountnaam.');await call('users.remove',{name:u.name,deleteHome:removeHome.i.checked});await open('users');})));}}if(config.user.admin){const name=input(),full=input(),pw=input('password'),repeat=input('password'),admin=check('Beheerder');root.append(card('Nieuw account',field('Gebruikersnaam',name),field('Volledige naam',full),field('Wachtwoord',pw),field('Herhaal wachtwoord',repeat),admin.node,button('Account toevoegen',async()=>{if(!/^[a-z_][a-z0-9_-]{0,31}$/.test(name.value))throw Error('Gebruik een geldige gebruikersnaam in kleine letters.');if(pw.value.length<6||pw.value!==repeat.value)throw Error('Gebruik minstens 6 tekens en twee gelijke wachtwoorden.');const password=pw.value;pw.value=repeat.value='';await call('users.add',{name:name.value,fullName:full.value,password,admin:admin.i.checked});await open('users');})));}else root.append(note('Accountbeheer vereist een beheerder.'));},
 shortcuts:async root=>{const list=await call('shortcuts.get'),inputs=new Map();for(const s of list){const i=input('text',s.key);i.disabled=!!s.fixed;inputs.set(s.id,i);root.append(field(s.name+(s.fixed?' (vast)':''),i));}root.append(note('W = Windows, C = Ctrl, S = Shift, A = Alt. Voorbeeld: W-e.'),button('Sneltoetsen opslaan',async()=>{const seen=new Set(),changes={};for(const s of list){const key=inputs.get(s.id).value.trim();if(!key||seen.has(key.toLowerCase()))throw Error('Elke sneltoets moet ingevuld en uniek zijn.');seen.add(key.toLowerCase());if(!s.fixed)changes[s.id]=key;}await call('shortcuts.set',{changes});}));},
 updates:async root=>root.append(card('Software en updates',updatesView(),note('Debian-updates komen van deb.debian.org en security.debian.org. Universe OS zelf heeft nog geen eigen updatebron.'),tool('Softwarewinkel openen voor installeren van updates','software',{mode:'updates'}),tool('Software beheren','software',{mode:'installed'}))),
 security:async root=>{const f=await call('firewall.get');root.append(card('Firewall',note(!f.installed?'Firewall niet geïnstalleerd.':f.enabled?'Firewall staat aan.':'Firewall staat niet actief.'),note('Inkomende verbindingen worden standaard geweigerd. De huidige regelset wordt hier niet weergegeven.')),card('Privacy',note('Persoonlijke mappen horen alleen voor hun eigenaar toegankelijk te zijn. Beheer accountrechten op de pagina Accounts.')));},
 about:async root=>{const a=await call('about');root.append(card('Universe OS',details(a,{universe:'Versie',base:'Linuxbasis',kernel:'Kernel',cpu:'Processor',memoryMB:'Geheugen (MB)',machine:'Computer',labwc:'Vensterbeheerder',secureBoot:'Secure Boot'}),note(a.efi?'Opgestart met UEFI.':'Niet opgestart met UEFI.')));}
};
function navigation(){const q=document.getElementById('search').value.toLowerCase();nav.replaceChildren();for(const s of SETTINGS.filter(v=>(v.name+' '+v.words).toLowerCase().includes(q))){const b=h('button',{type:'button','aria-current':s.id===current?'page':undefined},icon(s.icon),s.name);b.addEventListener('click',()=>open(s.id));nav.append(b);}}
async function open(id){if(!pages[id])id='appearance';current=id;const token=++generation;navigation();content.replaceChildren(h('h2',{},SETTINGS.find(s=>s.id===id).name),note('Laden…'));const root=h('div');try{await pages[id](root);}catch(e){root.append(h('p',{class:'message error',role:'alert'},e.message));}if(token===generation){content.replaceChildren(h('h2',{tabindex:-1},SETTINGS.find(s=>s.id===id).name),root);content.querySelector('h2').focus();}}
document.getElementById('search').addEventListener('input',navigation);
on('page',id=>{if(config)open(id);});
(async()=>{try{config=await call('config.get');applySettings({...config.settings,colors:config.world.colors});await open(await call('window.page'));}catch(e){content.replaceChildren(h('p',{role:'alert'},e.message));}})();
