font=Noto Sans 11
background-color=#0b1021f2
text-color=#e2e6fa
border-color=#85ffe3
border-size=2
border-radius=14
padding=14
margin=12
width=350
height=180
anchor=top-right
default-timeout=7000
max-visible=4

[urgency=critical]
border-color=#ff8a9a
default-timeout=0
