"""Writes this user's labwc configuration from the Universe settings (called at login and after changes).

labwc only manages the windows (move, resize, minimise, maximise, close, Alt+Tab); everything you see besides
the windows is the Universe shell. The configuration lives in ~/.config/universe-os/labwc (labwc -C).
"""
import os
import subprocess
from xml.sax.saxutils import quoteattr

import config

AUTOSTART = '''#!/bin/sh
# Started by labwc for the Universe OS session (generated by universe-os; changes are overwritten).
/usr/bin/universe-shell-supervisor &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XKB_DEFAULT_LAYOUT XKB_DEFAULT_VARIANT LANG LANGUAGE >/dev/null 2>&1 &
xdg-user-dirs-update >/dev/null 2>&1 &
/usr/libexec/polkit-mate-authentication-agent-1 >/dev/null 2>&1 &
mako --config /usr/share/universe-os/mako.conf >/dev/null 2>&1 &
/usr/lib/universe-os/universe-idle &
/usr/lib/universe-os/universe-displays apply >/dev/null 2>&1
'''

RECOVERY_AUTOSTART = '''#!/bin/sh
# Herstelmodus: alleen een terminal, zonder de Universe-shell.
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP >/dev/null 2>&1
/usr/libexec/polkit-mate-authentication-agent-1 >/dev/null 2>&1 &
mako --config /usr/share/universe-os/mako.conf >/dev/null 2>&1 &
(sleep 1; notify-send "Universe OS herstelmodus" "De ruimtewereld is niet gestart. Typ 'universe-shell' om hem te proberen, of 'exit' en kies opnieuw inloggen.") &
xfce4-terminal --title "Universe OS herstelmodus" &
'''


def _keybind(item):
    key = quoteattr(item['key'])
    extra = ' onRelease="yes"' if item.get('onRelease') else ''
    if item.get('labwc'):
        direction = ' direction=%s' % quoteattr(item['direction']) if item.get('direction') else ''
        action = '<action name="%s"%s/>' % (item['labwc'], direction)
    else:
        action = '<action name="Execute" command=%s/>' % quoteattr(item['command'])
    return '    <keybind key=%s%s>%s</keybind>' % (key, extra, action)


def rc_xml(recovery=False):
    s = config.settings()
    binds = [_keybind(item) for item in config.shortcuts()]
    if recovery:
        binds = [b for b in binds if 'universe-ctl' not in b] + ['    <keybind key="C-A-t"><action name="Execute" command="xfce4-terminal"/></keybind>']
    return '''<?xml version="1.0"?>
<!-- Gegenereerd door Universe OS uit ~/.config/universe-os (sneltoetsen en instellingen). Wijzigingen hier worden overschreven. -->
<labwc_config>
  <core><decoration>server</decoration><gap>0</gap><adaptiveSync>no</adaptiveSync><reuseOutputMode>yes</reuseOutputMode></core>
  <placement><policy>cascade</policy></placement>
  <theme>
    <name>Universe</name><cornerRadius>10</cornerRadius><keepBorder>yes</keepBorder><dropShadows>yes</dropShadows>
    <titlebar><layout>icon:iconify,max,close</layout><showTitle>yes</showTitle></titlebar>
    <font place="ActiveWindow"><name>Noto Sans</name><size>10</size><weight>bold</weight></font>
    <font place="InactiveWindow"><name>Noto Sans</name><size>10</size></font>
    <font place="OnScreenDisplay"><name>Noto Sans</name><size>11</size></font>
  </theme>
  <windowSwitcher show="yes" preview="yes" outlines="yes" allWorkspaces="yes">
    <fields><field content="icon" width="6%%"/><field content="title" width="94%%"/></fields>
  </windowSwitcher>
  <focus><followMouse>no</followMouse><raiseOnFocus>no</raiseOnFocus></focus>
  <snapping><range>10</range><topMaximize>yes</topMaximize></snapping>
  <desktops number="1"/>
  <keyboard>
    <repeatRate>25</repeatRate><repeatDelay>600</repeatDelay>
%s
  </keyboard>
  <mouse><default/></mouse>
  <libinput>
    <device category="default">
      <naturalScroll>%s</naturalScroll>
      <tap>%s</tap>
      <pointerSpeed>%.1f</pointerSpeed>
    </device>
  </libinput>
</labwc_config>
''' % ('\n'.join(binds), 'yes' if s['naturalScroll'] else 'no', 'yes' if s['tapToClick'] else 'no', s['pointerSpeed'])


def environment():
    kb = config.keyboard()
    s = config.settings()
    lines = [
        'XKB_DEFAULT_LAYOUT=%s' % kb['layout'],
        'XKB_DEFAULT_VARIANT=%s' % kb['variant'],
        'XKB_DEFAULT_OPTIONS=compose:ralt' if kb['layout'] == 'us' and kb['variant'] != 'intl' else 'XKB_DEFAULT_OPTIONS=',
        'XCURSOR_THEME=Adwaita',
        'XCURSOR_SIZE=24',
        'MOZ_ENABLE_WAYLAND=1',
        'QT_QPA_PLATFORM=wayland;xcb',
        '_JAVA_AWT_WM_NONREPARENTING=1',
        'UNIVERSE_UI_SCALE=%d' % s['uiScale'],
    ]
    return '\n'.join(lines) + '\n'


def write(recovery=False):
    target = os.path.join(config.user_dir(), 'labwc-recovery' if recovery else 'labwc')
    os.makedirs(target, exist_ok=True)
    files = {
        'rc.xml': rc_xml(recovery),
        'environment': environment(),
        'autostart': RECOVERY_AUTOSTART if recovery else AUTOSTART,
        # No root menu: right-click on the space world belongs to the world.
        'menu.xml': '<?xml version="1.0"?>\n<openbox_menu><menu id="root-menu" label=""/></openbox_menu>\n',
    }
    for name, content in files.items():
        path = os.path.join(target, name)
        with open(path + '.tmp', 'w', encoding='utf-8') as f:
            f.write(content)
        os.replace(path + '.tmp', path)
    os.chmod(os.path.join(target, 'autostart'), 0o755)
    return target


def reconfigure():
    write()
    if os.environ.get('LABWC_PID'):
        subprocess.run(['labwc', '--reconfigure'], check=False)


if __name__ == '__main__':
    import sys
    print(write(recovery='--herstel' in sys.argv))
