#!/bin/sh
# live-build configuratie voor het Universe OS live-ISO (Debian 13 trixie, amd64, UEFI).
# Gebruik: scripts/build-iso.sh (roept lb config / lb build aan in live/).
set -e

lb config noauto \
    --mode debian \
    --distribution trixie \
    --architectures amd64 \
    --linux-flavours amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap http://deb.debian.org/debian/ \
    --mirror-chroot http://deb.debian.org/debian/ \
    --mirror-binary http://deb.debian.org/debian/ \
    --mirror-chroot-security http://security.debian.org/debian-security/ \
    --mirror-binary-security http://security.debian.org/debian-security/ \
    --security true \
    --updates true \
    --binary-images iso-hybrid \
    --bootloaders grub-efi \
    --debian-installer none \
    --firmware-binary true \
    --firmware-chroot true \
    --apt-recommends false \
    --iso-application "Universe OS" \
    --iso-publisher "Universe OS - https://github.com/ItsAMeFork/universe-os" \
    --iso-volume "UNIVERSE_OS" \
    --image-name universe-os \
    --bootappend-live "boot=live components quiet splash locales=nl_NL.UTF-8 keyboard-layouts=us keyboard-variants=intl timezone=Europe/Amsterdam username=universe hostname=universe-live" \
    "${@}"
